# Generated by Django 4.1.7 on 2023-04-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='photo_url',
            field=models.URLField(max_length=500, null=True),
        ),
    ]
